### ISSUE TITLE
Enemy Behavior Tree Setup

### ISSUE THREAD

**Issue by lutca1320** [lutca1320/Together#41]
## Goal
Create Behavior of Doll
[Behavior Plan](https://github.com/lutca1320/Together/blob/master/README.md#doll-behavior)

## Task
- [x] Plan Behavior
- [x] Create Sound Zero Behavior
- [x] Create Sound Weak Behavior
- [x] Create Sound Middle Behavior
- [x] Create Sound Strong Behavior
