### ISSUE TITLE
Divide Area with Area Class

### ISSUE THREAD

**Issue by lutca1320** [lutca1320/Together#52]
## Goal
Create area class and apply for behavior tree

## Task
- [x] Setup Area_Interface
- [x] Connet Area and Game Instance
- [x] Place Area Classes
